### ISSUE TITLE
Not an issue (Does this support captcha)

### ISSUE THREAD

**Issue by ayamgupta** [yashwanthm/cowin-vaccine-booking#1]
Hi, 
Does this support captcha?

**Comment by yashwanthm** [comment]
No captha support required.

**Comment by lohithvadde** [comment]
Why the captcha support is not required ? Cowin app, now has a captcha and how are you bypassing it ?

**Comment by mukeshkmittal** [comment]
it is considering 45 years of Age under 18 to 45 range filter but 45 years of age should not be included under this category. plz check
