### ISSUE TITLE
App not catch open slots

### ISSUE THREAD

**Issue by sbhardwa123** [yashwanthm/cowin-vaccine-booking#10]
sometimes slot becomes available on Cowin but the app doesn't catch it. While I am able to attempt scheduling an appointment on Cowin site, on this app I do not get any notification that slots are now available. Any reason why this could be happening.

**Comment by yashwanthm** [comment]
Can you attach as screenshot of the network requets. 
My guess is that some of the requests to track availability are failing.

**Comment by yashwanthm** [comment]
Increased the polling freq to 3.2 seconds to handle it.

**Comment by ranjanwrites** [comment]
I received the open slots notification on telegram and was able to login in time on arogya setu but all the slots got filled. However, the same slots were not shown visible in the script. After 5-10 minutes the slots appeared as filled in the script. 

PS: I was constantly feeding the OTPs. I am not a techie and dont know which method you are using for catching the opening of slots, but it's not working. I bet with current configuration it's not possible to book an appointment using this script.

**Comment by yashwanthm** [comment]
Okay. You should not have such issues right now.
