### ISSUE TITLE
Slot for PIN Code 400060 were not visible & did not booked

### ISSUE THREAD

**Issue by RPAYNAIK** [yashwanthm/cowin-vaccine-booking#102]
I was logged in for complete day for Booking 2nd done slot in Pincode 400060, It did not got booked.

**Comment by hpk22** [comment]
Mail me at hrutvijkakade123@gmail.com
I'll help you get slot easily

**Comment by yashwanthm** [comment]
If the availability is detected, booking will automatically happen
