### ISSUE TITLE
Addition of new filter to Age Group for 18 above param

### ISSUE THREAD

**Issue by siddhesh1770** [yashwanthm/cowin-vaccine-booking#114]
Booking for 18 above param is not possible through current version 

Cowin data returns "allow_all_age":false      now please make changes

**Comment by siddhesh1770** [comment]
please let me know if you want help, I would love to look into

**Comment by yashwanthm** [comment]
Thank you for your interest @siddhesh1770 
Please go ahead and submit a pull request. I'll be happy to review and accept changes.
