### ISSUE TITLE
Not getting Cowin OPT after putting mobile no. 

### ISSUE THREAD

**Issue by RPAYNAIK** [yashwanthm/cowin-vaccine-booking#118]
Hi,
I am trying to login through this link for Vaccine booking, but I am not getting CoWIN OPT to login.

**Comment by DakshK579** [comment]
one fix is that you should not be connected to any vpn and your pc time should be as same as ist time 
and for the otp part you can get otp from selfrgistration.cowin.gov.in and then enter the same otp in this modded cowin portal and then all good
Thanks for reading

**Comment by yashwanthm** [comment]
Thanks Daksh.
Try not to request multiple OTPs unnecessarily.
