### ISSUE TITLE
Availability are not shown now, Tabular data is not visible

### ISSUE THREAD

**Issue by dgowda6** [yashwanthm/cowin-vaccine-booking#12]
This is a great work. Appreciate you with big thanks. There's an issue currently as the Availability data is not displayed.

![image](https://user-images.githubusercontent.com/9278211/117933581-5537a400-b31f-11eb-91f9-7a32d25a3d55.png)

**Comment by yashwanthm** [comment]
This is becuase there's no availability matching your preferences. Can you share a screenshot of your preferences?

**Comment by dgowda6** [comment]
![image](https://user-images.githubusercontent.com/9278211/117975875-c8a3da80-b34c-11eb-87e2-df1b9d7f9811.png)

**Comment by yashwanthm** [comment]
![image](https://user-images.githubusercontent.com/1220402/117976868-ddcd3900-b34d-11eb-91d0-deb04c3377c8.png)
Fixed now. Thanks for reporting.

**Comment by dgowda6** [comment]
Its Fixed. Thanks a Lot :)
