### ISSUE TITLE
Functional endpoint changes. 

### ISSUE THREAD

**Issue by mascot6699** [yashwanthm/cowin-vaccine-booking#15]
Encountered 401 while using the SearchByPin feature.

Looks like there is an endpoint change from [old](https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByPin) to [new](https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByPin)

Attaching postman collection for reference: [link](https://documenter.getpostman.com/view/9564387/TzRPip7u#49f061eb-20a9-471b-ad9e-e57fe743db60)

**Comment by yashwanthm** [comment]
I do notice these ocassional 401s, I think it's normal for it to happen during polling. 401 is probably not the right status but that's not in my control.
![image](https://user-images.githubusercontent.com/1220402/118071999-9040e280-b3c6-11eb-88c9-a6d8b715b94d.png)
