### ISSUE TITLE
Issue in displaying available slots when search Track by district

### ISSUE THREAD

**Issue by amiyonewgit** [yashwanthm/cowin-vaccine-booking#18]
Hi Yashwanth,

What I found is when I search by district it doesn't show the available slot and cpatcha, as soon as I search by pincode  it shows me the Captcha with the availability  but till then no slots avilable.

regards
Amiyo

**Comment by yashwanthm** [comment]
I've run into this issue myself. It's becuase the availability is running out before the captcha is entered. Keep trying.

**Comment by rdsoze** [comment]
@yashwanthm Based on someone's comments here: https://github.com/cowinapi/developer.cowin/issues/184#issuecomment-840514253
It seems that ```findByDistrict``` is perhaps not cached compared to ```calendarByDistrict```

**Comment by yashwanthm** [comment]
Need some help in validating what's better amongst findByDistrict and calendarByDistrict. Can you someone run tests and share data?

**Comment by sujoybhatt** [comment]
If `findByDistrict` doesnt cache data, wouldn't it be better to just call `findByDistrict` repeatedly for next 7 days instead of calling `calendarByDistrict`. Will take fractionally more time but the results will be more useful

**Comment by cowin-check** [comment]
Post login URL doesn't have "public" in it. me and @priteshshah010 told him to remove "public" from the url to fix cache issue. https://github.com/yashwanthm/cowin-vaccine-booking/issues/21 , https://github.com/yashwanthm/cowin-vaccine-booking/issues/3

![1](https://user-images.githubusercontent.com/83546235/118303692-5d503900-b503-11eb-9464-ce23bbcf980a.png)
--
![2](https://user-images.githubusercontent.com/83546235/118303696-5e816600-b503-11eb-8e2f-30e8dd0539cb.png)

**Comment by akashgurnani** [comment]
I think it should be done ASAP to get slots on a real-time basis.

**Comment by yashwanthm** [comment]
Thank you @cowin-check for the screenshot. Thank you @sujoybhatt @akashgurnani @amiyonewgit @rdsoze 
This has been updated and deployed.
