### ISSUE TITLE
Table not opening within 5 seconds after clicking on availability button.

### ISSUE THREAD

**Issue by yashtibrewal** [yashwanthm/cowin-vaccine-booking#19]
As per the docs https://github.com/yashwanthm/cowin-vaccine-booking/wiki/Usage-Guide
Point 6
"If you are not able to see the table within 5 seconds, then the tracking is not happening. Please refresh and start over. This can also happen when there are no vaccination centers in your pincode. Chaniging to district based tracking will help"
I do not see a pop-up as mentioned.
Moreover, I was using the bot to look for slots.
The slots opened ( as per notification from some other app : telegram group ) and the bot could not book it.
Please guide for the same.

**Comment by yashwanthm** [comment]
I think some people are mistaking the placeholder text with the actual value on the input.
I've made a fix for it. Try it now.

I'm not sure of what you mean by pop-up. If the app detects that the slots have opened up, it will speak up and show you the captcha.
