### ISSUE TITLE
Change in Slot Check API Url

### ISSUE THREAD

**Issue by priteshshah010** [yashwanthm/cowin-vaccine-booking#21]
Remove the Public Path from the slot check url
url should be https://cdn-api.co-vin.in/api/v2/appointment/sessions/calendarByPin?pincode=xxxxxx&date=xx-05-2021

**Comment by yashwanthm** [comment]
What's the difference @priteshshah010 ?

**Comment by priteshshah010** [comment]
Public APIs will have limited access and delay in real-time availability
Also change the delay in every ping to 3 seconds to avoid ip ban

*Best Regards,*
*Pritesh Shah*

**Comment by yashwanthm** [comment]
Thanks!
