### ISSUE TITLE
Even after entering OTP, The Availability of vaccine is showing from Cache

### ISSUE THREAD

**Issue by amiyonewgit** [yashwanthm/cowin-vaccine-booking#22]
![Capture](https://user-images.githubusercontent.com/84137919/118295198-342aab00-b4f9-11eb-8e76-eade3477f8da.JPG)

Hi Yashwanth,

After entering OTP, the data of vaccine availability is still showing from cache, which shouldn't be the case.
Please check why there is mismatch between live availability

Regards
Amiyo

**Comment by cowin-check** [comment]
Post login url doesn't have "public" in it. me and @priteshshah010 told him to remove "public" from the url to fix cache issue. https://github.com/yashwanthm/cowin-vaccine-booking/issues/21 , https://github.com/yashwanthm/cowin-vaccine-booking/issues/3
![1](https://user-images.githubusercontent.com/83546235/118301843-28db7d80-b501-11eb-9e19-7f5ee5562a01.png)

![2](https://user-images.githubusercontent.com/83546235/118301857-2b3dd780-b501-11eb-96e8-e0a223236b78.png)

**Comment by yashwanthm** [comment]
Cowin API is cahced and availability may show incorrectly for a few mins even after availability has run out. But when new availability comes in, app will try to make a booking attempt.
