### ISSUE TITLE
Update on the support for multiple selection of beneficiaries while scheduling.

### ISSUE THREAD

**Issue by mitra-surajit** [yashwanthm/cowin-vaccine-booking#26]
The https://app.cowin.gov.in/ has disabled the option to select multiple beneficiaries while scheduling. Does your app still support selection of multiple beneficiaries while scheduling ?

**Comment by yashwanthm** [comment]
As far as I can see, there's been no change on Cowin API. It should work with multiple beneficiaries.

**Comment by yashwanthm** [comment]
Confirmed by users just sometime ago that it still works.
