### ISSUE TITLE
Enable IFTTT support to auto-read OTPs

### ISSUE THREAD

**Issue by monizb** [yashwanthm/cowin-vaccine-booking#28]
Constantly feeding in new OTPs is tiresome, instead a scheduler should be used that automatically generates new OTPs and and IFTTT applet that auto detects this message and extracts OTP out of it

**Comment by yashwanthm** [comment]
Are you aware of an applet that allows the OTP available via an API call? @monizb

**Comment by hjawadwala** [comment]
how about trying to solve catch using AI and auto fill the captcha. so human just have to verify and hit submit

**Comment by yashwanthm** [comment]
Closing this as implementation would be a security concern.

**Comment by monizb** [comment]
> Are you aware of an applet that allows the OTP available via an API call? @monizb

Yes IFTTT already has an inbuilt method for call webhook on received message with a specific text, when set to "CoWIN" it will call the API endpoint automatically with the text message received, and the OTP can then be extracted from it on the backend
