### ISSUE TITLE
No slots available but still asking to book

### ISSUE THREAD

**Issue by niravsinha** [yashwanthm/cowin-vaccine-booking#33]
Currently there are no slots available for 560011 (18+ paid) but the bot shows 48 available. This has been confirmed from direct login on both Cowin and Argoyasetu
![CaptureA](https://user-images.githubusercontent.com/19818198/118610137-13a07080-b7d9-11eb-88c3-99053898c04a.JPG)

**Comment by yashwanthm** [comment]
Aware of this issues. It's a limitation from Cowin. The availability API responds back with availability for few mins after first publishing the availability. The API takes time to update the availability after the bookings run out. They are caching it for managing perforamnce and that's okay. 
Closing it as this is not fixable.
The problem usually goes away in a few minutes.
