### ISSUE TITLE
Keeps asking for captcha long after all slots are booked

### ISSUE THREAD

**Issue by ajayap278** [yashwanthm/cowin-vaccine-booking#35]
Even though all slots at this location are booked, It still keeps asking for a captcha for the same location even half-hour after the slots have been booked. 

By the way, thank you for the wonderful work.
<img width="947" alt="Untitled" src="https://user-images.githubusercontent.com/84381792/118631825-7dc31080-b7ed-11eb-991d-a95d720c017c.png">

**Comment by namanambavi** [comment]
Facing a similar issue since yesterday

**Comment by yashwanthm** [comment]
This is not fixable. The availability APIs are cached and continue to show availablity for a few minutes even after the availability is over.

**Comment by ajayap278** [comment]
Hi yashwanth, 

Thanks for the reply. I only raised this issue as the availability is being shown since morning (almost 8 hours now). If you are sure caching is the issue then no problem. Thanks again.

**Comment by yashwanthm** [comment]
There has been a bug with this. It's now fixed in the latest update.

**Comment by yashwanthm** [comment]
Thanks for reopening this. It got overlooked earlier.
