### ISSUE TITLE
Does it focus automatically on captcha

### ISSUE THREAD

**Issue by chetan1989-cloud** [yashwanthm/cowin-vaccine-booking#36]
I have not had a chance to enter captcha yet but does it automatically focus on captcha or we have to click on the text field manually?

**Comment by ajayap278** [comment]
I will automatically pull and display the captcha. You will have to enter it in the field and submit

**Comment by chetan1989-cloud** [comment]
Do I have click on the input textfield for captcha or the script automatically does that for me?

**Comment by yashwanthm** [comment]
Good point. I've added support for autofocus to captcha input when it appears.
