### ISSUE TITLE
Default Table in the results section 

### ISSUE THREAD

**Issue by vaccineuser** [yashwanthm/cowin-vaccine-booking#37]
While searching irrespective of the filter the full list of centre’s and availability/ for other age etc also shows up.. it’s a bit confusing, can we not restrict to show the list/ results only basis the filter given at time of running

**Comment by yashwanthm** [comment]
It's possible but, there is no selection of a vaccination centre for now. The table is for information only.
Centre selection is automatic.
Can consider this in future.
