### ISSUE TITLE
Broken paid/free filter

### ISSUE THREAD

**Issue by tonybenoy** [yashwanthm/cowin-vaccine-booking#39]
The filter for paid and free isn't working.
![image](https://user-images.githubusercontent.com/8504669/118776187-562f7f00-b8a5-11eb-8576-3c9be414d5ce.png)

**Comment by yashwanthm** [comment]
It's not broken, it just shows all kinds of availability for vaccination.
See the text above the table.

**Comment by tonybenoy** [comment]
@yashwanthm  so the booking filters are just for booking and not for filtering the data?

**Comment by yashwanthm** [comment]
Yes. 
Booking for center and slot is automatically selected as soon as there's availability.
I mean, if a user wants to select a center manually, they can totally do it on Cowin's portal.
