### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by SHEKHAR-SAHU-JAIPUR** [yashwanthm/cowin-vaccine-booking#40]
Hey Brother , You are working on public api or protected api (test server or production)

Because i am getting unauthorized access error , i am using protected test api , using free api given on cowin site and using updated bearer token

**Comment by yashwanthm** [comment]
The app uses a combination of both public and protected APIs.
What are the requests for which you are getting unathorized error?

**Comment by yashwanthm** [comment]
Dones't seem to be an issue concerning this app.
