### ISSUE TITLE
Is it possible to put Automatic CAPTCHA 

### ISSUE THREAD

**Issue by cutemahesh** [yashwanthm/cowin-vaccine-booking#43]
Sir,
I think sometimes when this web app shown for availability it requires captcha. Is it possible to put CAPTCHA before opening up of slot or captcha already display at ur web app during tracking and when the availability come at site and app speak when can just press the button of book. So I can get my slot. Cause what happened there is some delay in availability announcement by ur web app. Telegram notification come before ur app speaks. If captcha will be present and book on one step then good.
2. The umang app and arogya setu app proceed with no captcha. Umag app is fast than arogya setu. Umang is available on web portal also. Can u take or link api of umang with cowin , where without captcha booking can be possible
Pls do any stable solution. I am relying on ur web app from last two days. Availability come through telegram notification but app speak after it . And slot gone
 Pls try something

**Comment by yashwanthm** [comment]
There's very little that can be done.
Many users are trying to book their slots. The availability is running out
within a fraction of a second. Keep trying.
Thank you.
