### ISSUE TITLE
Can you please send desktop notification for session timeout and to enter captcha

### ISSUE THREAD

**Issue by sivagontla** [yashwanthm/cowin-vaccine-booking#44]
Can you please send desktop notification for session timeout and to enter captcha. It is really tough to be on earphones everytime.

setInterval of 1sec should do so that notifications will be pushed every second till the session gets established. Clear interval once session is back.

**Comment by yashwanthm** [comment]
That would be too intrusive. 
The app speaks out currently when it needs an OTP. However, there was no Desktop notifications to enter OTP. I've added it now.
