### ISSUE TITLE
Not refreshing the page for opened centers/slots

### ISSUE THREAD

**Issue by mukeshkmittal** [yashwanthm/cowin-vaccine-booking#45]
hi, this is not automatically refreshing the page or centers. new center added in Cowin but not showing in this application until unless you manually refresh the page. it means no automatic refresh is happening.

**Comment by yashwanthm** [comment]
The page doesn't refresh itself. Only the data is tracked continously.

**Comment by yashwanthm** [comment]
Closing this as a duplicate. Please go to https://github.com/yashwanthm/cowin-vaccine-booking/issues/42 for futher update.
