### ISSUE TITLE
New hospitals not updated in the list

### ISSUE THREAD

**Issue by Punee1994** [yashwanthm/cowin-vaccine-booking#46]
Few hospitals are getting updated in the portal which is not reflecting in this script

**Comment by sv1nz** [comment]
Faced the same problem now. Columbia Asia opened up slots, got the TG notification, but it didn't show up. The script was already running (OTP entered and was tracking), but it didn't detect the hospital nor the slots. 

Is there a delay?

**Comment by yashwanthm** [comment]
Dupliacate of https://github.com/yashwanthm/cowin-vaccine-booking/issues/42.
Would appreciate any help in debugging.
