### ISSUE TITLE
It is not generating OTP again

### ISSUE THREAD

**Issue by DixitJain546** [yashwanthm/cowin-vaccine-booking#48]
Once when we logged in and entered OTP, after that when the session got expired then again it is allowing to generate OTP 
-> I tried refreshing the page 
-> I tried reopening the tab 
-> I tried clearing the data of the site from browser setting 
But nothing worked for me

**Comment by yashwanthm** [comment]
This is a momentary issue. I've verified that it works now.
You have an option to cancel OTP entry just in case you get stuck there without an OTP.

**Comment by Jain-Abhilash** [comment]
This exact issue still persisting, Chrome on macOS, also tried on Safari as well as Chrome on Windows

**Comment by yashwanthm** [comment]
OTP generation fails when the load is too high on Cowin. You should retry in a few mins when it happens.
