### ISSUE TITLE
Something broken

### ISSUE THREAD

**Issue by Arvind369** [yashwanthm/cowin-vaccine-booking#49]
I was trying to book slot today  through pin code search for 18+ category.  Entered all the details and was waiting for availability prompt. I have also registered for Telegram notification developed by others. I started getting notification in Telegram for the pin code that I am searching in this app. This app was still looking for available slots. I thought it could be polling frequency, waited for few seconds but nothing happened. Stopped the search (track) and again initiated the track. The slots were already booked.  Now, for the second pin code, got notification in the Telegram, this app is still tracking, this time stopped and clicked track again, it found few slots, started asking Captcha,did not get confirmation, it started asking again and again with the new captcha. I am sure of giving the correct captcha.  Same thing happened for the 3rd pin code as well.

Note: I am using the app hosted by the author.

**Comment by kanishkkej** [comment]
Has anyone used this app successfully? I havent been able to book anything in a week.
