### ISSUE TITLE
Has anyone used this app successfully? I havent been able to book anything in a week

### ISSUE THREAD

**Issue by kanishkkej** [yashwanthm/cowin-vaccine-booking#51]
Once the app starts i dont see it updating the vaccine slots, by the time any notification comes on another platform, the slots are already booked without getting any notification from this app.

**Comment by yashwanthm** [comment]
https://twitter.com/souravmalani/status/1395211107569070082?s=19

https://www.linkedin.com/posts/activity-6801858578312433665-ApaL

https://www.linkedin.com/posts/yash-t-a3870889_finally-i-booked-a-vaccination-slot-activity-6799030041259884544-u-It
