### ISSUE TITLE
Split Tracking and Booking service

### ISSUE THREAD

**Issue by NaveenKS** [yashwanthm/cowin-vaccine-booking#55]
This is an idea to beat the control policy restriction set by Covin.

Track and book feature wouldn't be of much use since the OTP expires very soon due to control policy. I was thinking how about to do this way?

Split the features - OTP + booking and  searching slots(user validation not required) into two separate services. Search slot service would keep looking for slots every second and once it finds the slots a voice notification(with pincode) would let the user know that there is a slot found. OTP + booking service would be deployed in another server where user feeds the OTP and books using pincode. This way Covin won't be able to invalidate the OTP based on control policy.

**Comment by yashtibrewal** [comment]
Hi,
I have gone through the rate-limiting.
I have written a blog on it as well.
https://yash-tibrewal.medium.com/how-to-update-your-vaccination-slot-booking-app-with-the-latest-rate-limiter-70735d66c965
I have suggested some suggestions to @yashwanthm as well,
if the pollFreq = 3250 (Tested from morning today, worked flawlessly)
It will work flawlessly (not even 1 error you will face )
OTP sessions would be 15 minutes as standard.

Moreover, even the public APIs are restricted for 100 per 5 minutes per I.P.
hence changed anything other than pollFreq will do you now good.

Thanks

**Comment by yashwanthm** [comment]
@NaveenKS  Manual input is where the delays are and the availability runs out. 
Even if we'd do all the effort, I do not see it adding any value.

**Comment by NaveenKS** [comment]
@yashtibrewal Oh okay got it. 

@yashwanthm Okay.
