### ISSUE TITLE
Add functionality for comma-separated pin code entries 

### ISSUE THREAD

**Issue by uttsav** [yashwanthm/cowin-vaccine-booking#57]
Hey

Add functionality for comma-separated pin code entries 

This will be even better this app even better.

Utsav

**Comment by yashwanthm** [comment]
This will work in favour of the rate limits to track for multiple pincodes.

**Comment by vishnutsivan** [comment]
@yashwanthm Can you give more info/ steps to achieve this? Or can we have pin filter in a district? So that we can search by district every 1 minutes and book for preferred pins.

**Comment by yashwanthm** [comment]
Filtering for ziocode matches based on the results from a district seems to
be a good idea and it can work well while still complying with cowin's
guidelines.

However, this needs to be built.

**Comment by vishnutsivan** [comment]
Any update? are you developing this filter?
