### ISSUE TITLE
Select option for free or paid dose

### ISSUE THREAD

**Issue by subashjain** [yashwanthm/cowin-vaccine-booking#6]
If it’s possible please add to select free or paid dose

**Comment by yashwanthm** [comment]
it is possible to implement it but, I have not implemented it. I can accept pull requests if anyone is interested in adding that feature.

**Comment by yashwanthm** [comment]
`3c713e32cb70e7e0da499566cec5d66ef5c62641` has a fix for this. 
Refer to the deployed version 2021-05-11-16:32:48
