### ISSUE TITLE
Generating OTP fails without any user messages... 

### ISSUE THREAD

**Issue by mohan-the-octocat** [yashwanthm/cowin-vaccine-booking#62]
The login screen at times keep looping without generating any OTPs. 

This is noticeable mostly after the session times out and user attempts to login. Check out the attached clip. 

https://user-images.githubusercontent.com/83639549/119483160-4ff04580-bd72-11eb-9684-5e1ecfe38851.mov

**Comment by yashwanthm** [comment]
This happens when the rate limits are exhausted. It stars working again in 5 mins.
