### ISSUE TITLE
App is not tracking availability

### ISSUE THREAD

**Issue by vaibhav-random** [yashwanthm/cowin-vaccine-booking#63]
I've noticed it today, when I run the app it gives me 429. I was able to confirm my ip got blocked by running an other custom script from my local and got `429` there too. I think this is related to comment raised in https://github.com/yashwanthm/cowin-vaccine-booking/issues/5#issuecomment-848479094

**Comment by yashwanthm** [comment]
are you running mutliple tabs or devices?
If not, is it happening for every request? It should usually clear up after 5 mins. Please share screenshots with the debugger-network tab open.

**Comment by vaibhav-random** [comment]
I think it might be because we were running from multiple devices and the rate limiting based on ip
