### ISSUE TITLE
Reschedule not workin

### ISSUE THREAD

**Issue by maheshprasadr** [yashwanthm/cowin-vaccine-booking#68]
I already had a scheduled appointment but they didn't vaccinate saying it was jy for Frontline warriors at that time. Now in cowin it shows as rescheduled for me. When I try to booking via https://yashwanthm.github.io/cowin-vaccine-booking/ also added another member who was no apt before im not getting captcha though slots are open. Can you pls check.

**Comment by yashwanthm** [comment]
If cowin is showing as rescheduled, you should be able to download the appointment pdf. Please check the details there.

**Comment by maheshprasadr** [comment]
I can download the apt, I'm asking if this app will do the booking like "re-scedule" in cowin or only "schedule"?

**Comment by maheshprasadr** [comment]
There is no option to cancel on cowin, my apt was on May 22nd. Any idea how to cancel?

**Comment by maheshprasadr** [comment]
Sorry I could do that, have to click on X button to cancel
