### ISSUE TITLE
Point the cursor in otp box

### ISSUE THREAD

**Issue by ranthwar-livemeet** [yashwanthm/cowin-vaccine-booking#69]
Really appreciate your hardwork...

when ever we get OTP please put the pointer inside the box..right now we need to select textbox of otp and then need to enter otp...

this might be quick fix..:)

**Comment by yashwanthm** [comment]
Great suggestion! Will add this.

**Comment by ranthwar-livemeet** [comment]
Thanks @yashwanthm
