### ISSUE TITLE
Tried this for 2 days. Sadly if didn't even notify me once

### ISSUE THREAD

**Issue by rrrrravichandra3** [yashwanthm/cowin-vaccine-booking#70]
I noticed this app didn't even notify me once when the slots got opened. I subscribed to telegram alerts to know the availability. I received many alerts from telegram and this app didn't pick any of that. It didn't notify me at all.

These are the following steps that  I followed : 

1. Went to https://yashwanthm.github.io/cowin-vaccine-booking/, fed phone number, otp and selected my beneficiary and booking preferences.
2. Filled the needed details and clicked on track button.
3. I fed the otp to the app whenever it prompted me to.

May I know if I am doing anything wrong.

On what basis does your app selects the slot while booking

**Comment by yashwanthm** [comment]
@rrrrravichandra3  You might be stuck with caching issue. 
Try changing the tracking mode. There's a check box to toggle this.
Hope this helps.
