### ISSUE TITLE
Error after entering captcha

### ISSUE THREAD

**Issue by sit1abhi123** [yashwanthm/cowin-vaccine-booking#71]
Tried booking. After entering captcha it says this reference xxxxxxxxxxx number is not linked with registered mobile number xxxxxxxx

**Comment by yashwanthm** [comment]
Login into cowin and get it rectified.
After that, come back to this app and start over. Try clearing site data on the browser for this site if the issue still persists.

**Comment by 2704samir** [comment]
Your app works and i have gotten myself vaccinated through this, been trying to book a slot for a friend of mine but its failing and the same reference number issue is popping up, have tried re-registering on cowin too. Please guide, thank you.

**Comment by yashwanthm** [comment]
Thanks for notifying this @2704samir. 
I'm unsure about how the old appointment ID shows up. The IDs might look similar but won't be the same. 

However, I've added a minor fix for handling any such cases. Can you try it again?

**Comment by 2704samir** [comment]
Thank you. I will try again and update

**Comment by 2704samir** [comment]
It has worked, booked 2 slots for my friends. Thank you. I have donated a small amount for your extremely useful work.

**Comment by yashwanthm** [comment]
Thank you @2704samir

**Comment by sit1abhi123** [comment]
![cowin](https://user-images.githubusercontent.com/34596589/120181973-66434900-c22b-11eb-8ab0-77ac8586af04.jpg)
Same error occurred today. Immediately I logout and Relogging but same error.

> Tried booking. After entering captcha it says this reference xxxxxxxxxxx number is not linked with registered mobile number xxxxxxxx

**Comment by yashwanthm** [comment]
@sit1abhi123 Try logging out and then login again.
