### ISSUE TITLE
Available slots not detected

### ISSUE THREAD

**Issue by gps202** [yashwanthm/cowin-vaccine-booking#73]
I found the app is not able to notify slots for Covaxin option. had few instances i dint get the prompt. used the laternative tracking option but still dint work.

**Comment by yashwanthm** [comment]
Edited the issue and keeping this open for other users to find help.

**Comment by deepsen84** [comment]
Same case with me. I had my wife and my account against the same number and I was trying to block a slot for both together and everytime the Covaxin slots came and went without any prompt. So I decided to have 2 different laptops to try it  and have just 1 person checked in 1 laptop and my wife got the slot but nothing came to me again.
Today, I tried for just me and again 2-3 Covaxin slots came and went without any prompt. Unable to figure out what the issue could be

**Comment by yashwanthm** [comment]
@deepsen84  Different laptops connected to the same internet connection will not help. 
You can use your mobile instead by using mobile data.
Having multiple beneficiaries checked in is not a problem.

The app checks once in 3 seconds. In my observation, Covaxins are running out very quickly. Availability is coming and getting finished within that window. You'll just have to keep trying.

**Comment by deepsen84** [comment]
Thanks. 
Can I connect on your site from multiple laptops(different internet connection/IP) against the same phone number? Does that allow/ does that work?

**Comment by yashwanthm** [comment]
Yes, that will work fine.

**Comment by rayarindam2111** [comment]
Great improvisation!
The UMANG api, however does not require a captcha for booking vaccine slots.
You can try this project out: [Co-WIN-automated-slot-booking](https://github.com/rayarindam2111/Co-WIN-automated-slot-booking).
