### ISSUE TITLE
Date Range for booking instead of one day

### ISSUE THREAD

**Issue by Madaditya** [yashwanthm/cowin-vaccine-booking#74]
Hi @yashwanthm 

First, thank you for this awesome setup! 
Just needed to suggest one feature - can we have a **date range** to look for slots intead of one specific day ? This will allow people who need to get vaccinated urgently to get a fixed slot in next few days.

Let me know if I can PR and help.

**Comment by yashwanthm** [comment]
Turning off the alternative tracking allows for search of upto 7 days from the selected date. @Madaditya 
Try it out.
