### ISSUE TITLE
Didn't prompt for Captcha Entry; Bad Slot Timing

### ISSUE THREAD

**Issue by Eihcra** [yashwanthm/cowin-vaccine-booking#83]
I tried using this when my friend managed to book it, but when I tried booking a slot for Mumbai district at 12:30PM, it booked a slot for me with preferred hour of 10-11AM, and the vaccine slot was ending at 1PM. 

I thought I would get the opportunity to cancel it if the slot/centre was not ideal, or at least skip the captcha, but it straight up booked a slot without warning, which was going to end the same hour I booked it, and the centre was nearly an hour or two away.

**Comment by yashwanthm** [comment]
Yeah.. one way to avoid it is to select next day. If you are searching for availability the same day. This can very likely happen.
Try checking with the vaccination center and let them know that you might be delayed.

If you choose not to get vaccinated today, then I do not know how Cowin is going to handle this. Keep me posted either way. @Eihcra

**Comment by Eihcra** [comment]
Yeah I guess it was partly my fault. But also now with the lack of a captcha, this deters people from booking slots using a script which would allow us to pick and choose. Unless the script asked for confirmation.

So the next day I went ahead and just cancelled the appointment. I'll just need to reschedule it, it seems. It'd be great to know if you're working on a confirmation layer before booking so people using it would be able to pick a convenient slot, instead of getting something that's at the other end of the city.

**Comment by yashwanthm** [comment]
@Eihcra I think a confirmation if any should be before starting tracking. 
Becuase, if you try to confirm after the availability is detected.

I've added a slight change to text on the track avaialbility and book button. It now says "Track Availability & Auto-Book for selected preferences"
