### ISSUE TITLE
Show the results that match preferences only.

### ISSUE THREAD

**Issue by ravirajlondhepatil** [yashwanthm/cowin-vaccine-booking#86]
Hi,
Great tool, thanks.
Just one enhancement I would request is, when we start tracking and booking below list should be as per our preferences. So that we can identify if our selection done is correct.

thanks in advance.

**Comment by yashwanthm** [comment]
@ravirajlondhepatil You have my vote.

**Comment by yashwanthm** [comment]
Fix is underway. @ravirajlondhepatil  Let me know if there are any issue with the latest update.

**Comment by yashwanthm** [comment]
I've tried this and a lot of users have been misled to think that the tracking is not activated.

**Comment by ravirajlondhepatil** [comment]
@yashwanthm Oh then it's okay, anyway thanks for your efforts
