### ISSUE TITLE
Users are getting blocked and not recieving OTP

### ISSUE THREAD

**Issue by yashwanthm** [yashwanthm/cowin-vaccine-booking#96]
If you have any issues related to getting blocked on unable to login onto Cowin, please add a comment here.

**Comment by arun-thekkuden** [comment]
HTTP 403 after a few minutes of running

**Comment by chrissmartin** [comment]
Yup getting 403, I guess with recent terms change they are blocking if more than 20 requests in 15min window. I saw the other post, so if you get approval then cool

**Comment by yashwanthm** [comment]
Adjusted the polling freqency to have 20 requests per 15 mins. It will prove to be less effective but, let's try this variant out until the formal access is complete.

**Comment by Jacobs4** [comment]
It's show some errors in after login with otp

**Comment by Hibrajesh** [comment]
I have not received OTP

**Comment by yashwanthm** [comment]
App is now compliant with updates rate limits. Please refer to the Usage Guide and FAQs section for a better experience.

**Comment by shreysh-mane** [comment]
The site showed that the slot was available but it didn't booked the slot.

**Comment by Dragoon1223** [comment]
The slots aren’t getting booked now. The app isn’t working anymore unfortunately. It was working perfectly fine a while back. Now even though vaccines are showing up it isn’t getting booked. Keeps showing tracking.

**Comment by yashwanthm** [comment]
> The slots aren’t getting booked now. The app isn’t working anymore unfortunately. It was working perfectly fine a while back. Now even though vaccines are showing up it isn’t getting booked. Keeps showing tracking.

@Dragoon1223  It's working fine. Please keep trying. 
Tracking and booking attempts are made once in 45 seconds.

**Comment by SanjayRanjiniRaju** [comment]
Is it possible to edit he code so that multiple pincodes can be entered and looked for ?

**Comment by RPAYNAIK** [comment]
unable to login onto Cowin, not getting OTP

**Comment by samarpon97320** [comment]
Please contact me i have a offer for you to develop a game. Please help whatsapp 9126318483

**Comment by go4dev** [comment]
Do you have link for 15 years children?
