### ISSUE TITLE
Getting Error " Booking Not done required array length 1-4" 

### ISSUE THREAD

**Issue by ravikachhwaha3** [yashwanthm/cowin-vaccine-booking#97]
Getting Error " Booking Not done required array length 1-4"  Something like that. i am not able to understand that what it is.

**Comment by ravikachhwaha3** [comment]
i also  aware that i have selected beneficiary,  and i also tried logout and after relogin again.... but getting same error.

**Comment by yashwanthm** [comment]
I'm not sure why this error happens despite selecting beneficiaries. 
Are you able to book on Cowin? @ravikachhwaha3

**Comment by ravikachhwaha3** [comment]
I haven't tried... But i have discuss  with my friend he also face issue, but he realize this problem normally occured when the simultaneously login in arogya setu mobile app. May be ... And cowin also update ...now a person can registered only with one mobile number .. and cannot register with another number..

**Comment by yashwanthm** [comment]
Yes, it's better to have one beneficiary from one number only.

**Comment by ravikachhwaha3** [comment]
Thank you brother...highly appreciated

**Comment by ravikachhwaha3** [comment]
Thanks a lot
