### ISSUE TITLE
Not track immediate availability

### ISSUE THREAD

**Issue by Raman9944** [yashwanthm/cowin-vaccine-booking#98]
Sir, your yesterday update dated 13/06/21 lead delay availability search.
Not search immediate available seat.
Please resolve

**Comment by kamalguptas** [comment]
Yes, faced same....even i tried manually i got my slot but still website didn't found the slot !!!

**Comment by yashwanthm** [comment]
The polling frequency had been reduced to comply with rate limits and stop
users from getting blocked. This is expected.

If you think the app is not picking availability, then please stop and
start tracking or change tracking mode.

**Comment by Raman9944** [comment]
Although speaker earier says every time slots available at specific center.
But now speaker speaks only one time slots available then stop not repeat but earlier speaker repeats tills available slots till Nil.

**Comment by yashwanthm** [comment]
If you are logged in, the app will book it. Otherwise, it will wait as soon as availability is detected. @Raman9944
